In [1]:
import pandas as pd

# loading both datasets
qs = pd.read_csv("qs_clean.csv")
cost = pd.read_csv("cost_country.csv")

In [2]:
qs

,Country,Region,Research,Academic_Reputation,Employer_Reputation,Research_Quality,Employment_Outcomes
0,United States of America,Americas,VH,100.0,100.0,100.0,100.0
1,United Kingdom,Europe,VH,99.6,100.0,95.0,95.9
2,United States of America,Americas,VH,100.0,100.0,99.7,100.0
3,United Kingdom,Europe,VH,100.0,100.0,91.0,100.0
4,United States of America,Americas,VH,100.0,100.0,100.0,100.0
...,...,...,...,...,...,...,...
1496,Czechia,Europe,VH,7.2,5.3,7.9,15.5
1497,Russian Federation,Europe,HI,5.7,4.7,1.6,3.5
1498,Thailand,Asia,MD,8.3,2.7,5.6,3.2
1499,Japan,Asia,HI,4.4,2.9,8.2,1.7
1500,Republic of Korea,Asia,MD,6.5,11.9,2.0,1.9

In [3]:
qs_country = qs.groupby("Country").agg({
    "Academic_Reputation": "mean",
    "Employer_Reputation": "mean",
    "Research_Quality": "mean",
    "Employment_Outcomes": "mean"
}).reset_index()

In [4]:
df = pd.merge(qs_country, cost, on="Country", how="inner")

In [5]:
df

,Country,Academic_Reputation,Employer_Reputation,Research_Quality,Employment_Outcomes,Tuition_USD,Living_Cost_Index,Rent_USD
0,Argentina,23.266667,23.383333,2.288889,29.466667,0.000000,39.616667,293.333333
1,Australia,39.483333,34.702778,70.697222,34.700000,34610.465116,68.245349,1361.627907
2,Austria,30.537500,21.962500,24.575000,37.950000,1500.000000,71.066667,794.444444
3,Bahrain,19.666667,18.133333,6.600000,26.500000,7600.000000,62.860000,630.000000
4,Bangladesh,12.653333,23.153333,10.200000,13.833333,2220.000000,38.960000,192.000000
5,Belgium,38.110000,26.530000,51.590000,50.580000,3566.666667,71.311111,827.777778
6,Brazil,27.479167,15.675000,13.625000,27.879167,1000.000000,50.237500,466.250000
7,Bulgaria,16.000000,25.200000,3.100000,88.600000,3200.000000,44.960000,340.000000
8,Canada,35.551724,34.462069,51.803448,50.448276,29456.578947,62.950000,1167.763158
9,Colombia,32.338462,36.361538,4.476923,39.600000,3550.000000,36.983333,313.333333
10,Croatia,12.700000,10.133333,8.533333,45.366667,3583.333333,55.050000,390.000000
11,Cyprus,11.350000,7.850000,51.050000,32.950000,7750.000000,60.966667,501.666667
12,Denmark,50.840000,33.900000,69.440000,57.340000,1720.000000,73.720000,1103.333333
13,Dominican Republic,3.950000,6.900000,1.800000,50.750000,5160.000000,39.040000,288.000000
14,Ecuador,16.271429,13.142857,4.871429,16.257143,7360.000000,42.640000,330.000000
15,Egypt,17.700000,17.715000,5.105000,20.790000,4700.000000,31.142857,232.857143
16,Finland,31.222222,23.122222,56.666667,39.277778,0.000000,70.927273,859.090909
17,France,29.931429,21.482857,33.411429,28.308571,4633.333333,71.651852,1061.111111
18,Germany,36.329167,33.643750,41.595833,27.458333,177.272727,67.981818,956.060606
19,Ghana,14.000000,10.800000,7.350000,73.350000,4000.000000,38.520000,232.000000
20,Greece,22.414286,30.328571,47.457143,33.614286,147.058824,60.941176,475.882353
21,Hungary,16.830000,20.260000,9.520000,21.070000,5600.000000,46.887500,356.250000
22,Iceland,9.600000,2.000000,18.000000,89.300000,0.000000,81.750000,1016.666667
23,India,18.492593,24.927778,43.707407,17.333333,1900.000000,43.375000,312.500000
24,Indonesia,25.453846,30.653846,2.546154,22.361538,3900.000000,41.487500,298.750000
25,Ireland,40.137500,40.450000,36.037500,49.000000,17890.000000,71.710000,1130.000000
26,Israel,27.766667,26.200000,56.300000,57.400000,12000.000000,76.200000,1200.000000
27,Italy,27.018605,17.025581,50.146512,19.004651,3576.470588,69.882353,970.588235
28,Japan,27.517021,31.104255,19.374468,20.668085,7875.000000,68.025000,758.333333
29,Kuwait,20.900000,22.433333,8.333333,38.333333,11800.000000,67.280000,716.000000
30,Lebanon,18.244444,32.611111,8.455556,30.066667,14200.000000,54.540000,474.000000
31,Luxembourg,13.200000,8.200000,39.500000,58.800000,400.000000,78.900000,1185.714286
32,Malaysia,29.053125,34.309375,19.600000,11.709375,7220.000000,51.420000,433.000000
33,Mexico,22.931818,23.018182,2.586364,26.940909,5700.000000,46.011111,506.666667
34,Morocco,9.700000,3.100000,10.750000,40.400000,1950.000000,40.233333,280.000000
35,Netherlands,55.769231,49.769231,73.053846,53.907692,13523.809524,71.004762,1004.761905
36,New Zealand,46.362500,29.275000,57.900000,64.775000,29333.333333,72.866667,1005.555556
37,Nigeria,9.100000,14.166667,4.900000,82.466667,2500.000000,40.200000,400.000000
38,Norway,31.383333,17.016667,31.933333,49.050000,0.000000,72.327273,1036.363636
39,Panama,9.000000,13.150000,1.200000,35.200000,6600.000000,46.440000,436.000000
40,Peru,19.722222,25.100000,2.066667,21.744444,7250.000000,40.433333,288.333333
41,Poland,17.315000,21.485000,11.200000,15.540000,2762.500000,50.775000,566.250000
42,Portugal,29.111111,26.811111,48.988889,42.833333,5900.000000,58.100000,586.666667
43,Romania,10.900000,17.410000,8.040000,19.910000,2185.714286,41.785714,361.428571
44,Saudi Arabia,19.909091,20.050000,22.195455,16.654545,4790.000000,65.450000,681.000000
45,Serbia,18.050000,10.250000,8.500000,64.550000,2520.000000,44.960000,304.000000
46,Singapore,56.850000,57.075000,73.100000,57.775000,34172.222222,82.022222,1394.444444
47,Slovenia,14.700000,13.400000,10.666667,50.866667,4140.000000,58.000000,430.000000
48,South Africa,23.345455,28.136364,36.109091,66.372727,5900.000000,49.200000,600.000000
49,Spain,29.260526,28.163158,21.300000,28.792105,3188.235294,66.788235,814.705882
50,Sweden,51.712500,42.175000,60.100000,66.150000,0.000000,70.860000,925.000000
51,Switzerland,45.780000,37.690000,65.270000,52.860000,1460.000000,97.820000,1690.000000
52,Taiwan,24.992593,28.555556,29.322222,26.496296,5200.000000,62.800000,700.000000
53,Thailand,28.620000,20.106667,7.866667,21.040000,9850.000000,44.787500,325.000000
54,Tunisia,11.225000,5.025000,5.300000,35.700000,1400.000000,32.266667,185.000000
55,Ukraine,10.040000,26.830000,2.450000,22.990000,3520.000000,42.760000,340.000000
56,Uruguay,24.075000,23.475000,1.650000,34.600000,2700.000000,48.880000,382.000000
57,Uzbekistan,23.614286,25.242857,2.000000,19.671429,3620.000000,40.360000,230.000000

In [6]:
df.shape

(58, 8)

In [7]:
df.isnull().sum()

Country                0
Academic_Reputation    0
Employer_Reputation    0
Research_Quality       0
Employment_Outcomes    0
Tuition_USD            0
Living_Cost_Index      0
Rent_USD               0
dtype: int64

In [8]:
df.to_csv("final_df.csv", index=False)