In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv(r"C:\Users\DURVA\Downloads\archive (3)\2026 QS World University Rankings.csv")

In [3]:
df

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1496,1401+,1201-1400,University of West Bohemia,Czechia,Europe,M,CO,VH,Public,7.2,...,801+,4.8,801+,40.9,801+,15.5,801+,19.5,801+,-
1497,1401+,1201-1400,Voronezh State University,Russian Federation,Europe,L,CO,HI,Public,5.7,...,546,40.2,502,12.2,801+,3.5,801+,20.4,801+,-
1498,1401+,NaN,Walailak University,Thailand,Asia,L,FC,MD,Public,8.3,...,801+,7.4,801+,31.5,801+,3.2,801+,43.0,801+,-
1499,1401+,1201-1400,Yamaguchi University,Japan,Asia,M,FC,HI,Public,4.4,...,801+,8.9,801+,15.4,801+,1.7,801+,22.5,801+,-
1500,1401+,1201-1400,Youngsan University,Republic of Korea,Asia,M,SP,MD,Private for Profit,6.5,...,658,24.7,689,2.5,801+,1.9,801+,11.5,801+,-

In [4]:
df.dtypes

2026 Rank             object
Previous Rank         object
Institution Name      object
Country/Territory     object
Region                object
Size                  object
Focus                 object
Research              object
Status                object
AR SCORE             float64
AR RANK               object
ER SCORE             float64
ER RANK               object
FSR SCORE            float64
FSR RANK              object
CPF SCORE            float64
CPF RANK              object
IFR SCORE            float64
IFR RANK              object
ISR SCORE            float64
ISR RANK              object
ISD SCORE            float64
ISD RANK              object
IRN SCORE            float64
IRN RANK              object
EO SCORE             float64
EO RANK               object
SUS SCORE            float64
SUS RANK              object
Overall SCORE         object
dtype: object

In [5]:
df.describe()

,AR SCORE,ER SCORE,FSR SCORE,CPF SCORE,IFR SCORE,ISR SCORE,ISD SCORE,IRN SCORE,EO SCORE,SUS SCORE
count,1501.000000,1501.000000,1501.000000,1501.000000,1414.000000,1464.00000,1464.000000,1499.000000,1501.000000,1477.000000
mean,25.785943,26.944237,33.950433,30.425516,36.305658,33.32541,34.526981,53.356905,29.989674,51.254367
std,24.500905,25.504494,28.440071,29.679882,35.252024,32.75066,31.108600,28.920632,29.197573,21.266331
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,3.000000
25%,8.800000,8.500000,10.800000,6.000000,6.600000,5.90000,8.675000,27.500000,6.200000,35.700000
50%,16.000000,16.500000,23.500000,18.000000,20.100000,19.40000,21.700000,55.800000,17.900000,48.700000
75%,32.700000,37.500000,50.500000,49.700000,66.100000,56.70000,55.650000,78.500000,46.000000,66.500000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000

In [6]:
# dropping the rank columns because the score columns has the same thing
# score values are continuous numeric values
df.drop(columns=[
    "AR RANK","ER RANK","FSR RANK","CPF RANK",
    "IFR RANK","ISR RANK","ISD RANK","IRN RANK",
    "EO RANK","SUS RANK"
], inplace=True)

In [7]:
df.isnull().sum()

2026 Rank              0
Previous Rank        112
Institution Name       0
Country/Territory      0
Region                 0
Size                   1
Focus                  0
Research               1
Status                47
AR SCORE               0
ER SCORE               0
FSR SCORE              0
CPF SCORE              0
IFR SCORE             87
ISR SCORE             37
ISD SCORE             37
IRN SCORE              2
EO SCORE               0
SUS SCORE             24
Overall SCORE          0
dtype: int64

In [8]:
# dropping columns which are not the primary decision factors for a student to choose a country.
# keeping features like academic quality and job prospects while dropping less useful rank-based details.
df.drop(columns=[
    "2026 Rank",
    "Previous Rank",
    "IFR SCORE","ISR SCORE","ISD SCORE","IRN SCORE","SUS SCORE",
    "Status","Institution Name",
    "Focus","Overall SCORE",
    "Size","FSR SCORE"], inplace=True)

In [9]:
df.isnull().sum()

Country/Territory    0
Region               0
Research             1
AR SCORE             0
ER SCORE             0
CPF SCORE            0
EO SCORE             0
dtype: int64

In [10]:
df

,Country/Territory,Region,Research,AR SCORE,ER SCORE,CPF SCORE,EO SCORE
0,United States of America,Americas,VH,100.0,100.0,100.0,100.0
1,United Kingdom,Europe,VH,99.6,100.0,95.0,95.9
2,United States of America,Americas,VH,100.0,100.0,99.7,100.0
3,United Kingdom,Europe,VH,100.0,100.0,91.0,100.0
4,United States of America,Americas,VH,100.0,100.0,100.0,100.0
...,...,...,...,...,...,...,...
1496,Czechia,Europe,VH,7.2,5.3,7.9,15.5
1497,Russian Federation,Europe,HI,5.7,4.7,1.6,3.5
1498,Thailand,Asia,MD,8.3,2.7,5.6,3.2
1499,Japan,Asia,HI,4.4,2.9,8.2,1.7
1500,Republic of Korea,Asia,MD,6.5,11.9,2.0,1.9

In [11]:
obj_cols = df.select_dtypes(include='object').columns
for col in obj_cols:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

Country/Territory:
Country/Territory
United States of America    192
United Kingdom               90
China (Mainland)             72
India                        54
Germany                      48
                           ...
Luxembourg                    1
Ethiopia                      1
Malta                         1
Iceland                       1
Libya                         1
Name: count, Length: 106, dtype: int64

Region:
Region
Asia        565
Europe      487
Americas    358
Africa       47
Oceania      44
Name: count, dtype: int64

Research:
Research
VH     1056
HI      354
MD       80
LO       10
NaN       1
Name: count, dtype: int64

In [12]:
df[df["Research"].isna()]

,Country/Territory,Region,Research,AR SCORE,ER SCORE,CPF SCORE,EO SCORE
1240,Iran (Islamic Republic of),Asia,NaN,6.1,5.0,8.5,35.7

In [13]:
df["Research"].fillna("Unknown", inplace=True)

In [14]:
df.isnull().sum()

Country/Territory    0
Region               0
Research             0
AR SCORE             0
ER SCORE             0
CPF SCORE            0
EO SCORE             0
dtype: int64

In [15]:
for col in df.columns:
    print(f"\n{col} ({df[col].nunique()})")
    print(df[col].unique())

Country/Territory (106)
['United States of America' 'United Kingdom' 'Switzerland' 'Singapore'
 'Hong Kong SAR, China' 'China (Mainland)' 'Australia' 'Germany' 'Canada'
 'France' 'Japan' 'Republic of Korea' 'Netherlands' 'Malaysia' 'Belgium'
 'Taiwan' 'New Zealand' 'Saudi Arabia' 'Sweden' 'Ireland' 'Argentina'
 'Italy' 'Denmark' 'Russian Federation' 'Brazil' 'Qatar' 'Finland' 'Chile'
 'Norway' 'India' 'Mexico' 'South Africa' 'Austria' 'Spain' 'Kazakhstan'
 'United Arab Emirates' 'Indonesia' 'Colombia' 'Thailand' 'Israel'
 'Portugal' 'Lebanon' 'Czechia' 'Türkiye' 'Poland' 'Macao SAR, China'
 'Iran (Islamic Republic of)' 'Jordan' 'Oman' 'Peru' 'Egypt' 'Pakistan'
 'Greece' 'Estonia' 'Philippines' 'Brunei Darussalam' 'Luxembourg'
 'Lithuania' 'Belarus' 'Cyprus' 'Uzbekistan' 'Viet Nam' 'Costa Rica'
 'Slovenia' 'Kuwait' 'Hungary' 'Iceland' 'Bangladesh' 'Bahrain' 'Uruguay'
 'Slovakia' 'Azerbaijan' 'Northern Cyprus' 'Croatia' 'Ukraine' 'Bulgaria'
 'Venezuela (Bolivarian Republic of)' 'Tunisia' 'Iraq' 'Malta' 'Romania'
 'Latvia' 'Serbia' 'Cuba' 'Ecuador' 'Ethiopia' 'Ghana' 'Kyrgyzstan'
 'Palestine' 'Georgia' 'Uganda' 'Puerto Rico' 'Sri Lanka' 'Nigeria'
 'Kenya' 'Armenia' 'Syrian Arab Republic' 'Dominican Republic' 'Guatemala'
 'Paraguay' 'Panama' 'Morocco' 'Sudan' 'Bosnia and Herzegovina' 'Honduras'
 'Libya']

Region (5)
['Americas' 'Europe' 'Asia' 'Oceania' 'Africa']

Research (5)
['VH' 'HI' 'MD' 'LO' 'Unknown']

AR SCORE (554)
[100.   99.6  99.7  99.9  98.3  99.3  97.1  99.8  98.9  99.5  96.3  92.7
  92.   93.2  98.1  82.6  93.7  96.2  97.9  94.2  98.6  95.7  58.1  92.2
  94.3  89.4  86.2  87.   91.6  87.3  80.1  92.5  81.2  80.6  92.3  93.
  89.2  92.9  75.5  97.7  91.7  94.   53.5  97.6  72.4  75.3  82.7  82.5
  81.1  69.   60.2  88.3  87.1  90.1  78.3  86.1  85.   81.8  62.6  74.3
  90.5  73.   74.7  74.1  70.9  58.7  75.4  57.1  83.4  71.   85.5  61.3
  72.1  79.3  83.7  57.7  44.8  97.3  84.5  63.6  85.7  43.3  61.5  57.5
  72.7  98.   74.5  66.5  80.4  50.6  67.8  53.   76.   67.9  55.1  68.4
  76.2  90.7  73.3  68.3  48.9  57.6  75.7  77.6  99.2  62.9  90.6  47.7
  40.5  49.4  72.2  54.8  72.9  64.6  61.2  65.1  67.2  60.7  58.2  42.3
  82.3  64.   55.   57.9  55.3  51.2  34.   84.9  67.3  68.2  67.5  74.2
  34.6  46.5  66.1  56.8  71.5  71.3  76.4  63.9  52.5  91.9  67.   34.3
  45.2  65.3  60.1  34.5  46.3  38.   41.6  53.6  69.9  78.5  71.1  50.9
  61.7  45.7  53.3  73.6  60.   47.6  42.1  49.6  46.4  66.4  29.3  41.7
  73.1  67.7  57.2  68.6  81.5  58.9  37.   61.   42.5  65.5  47.2  56.6
  35.8  82.   43.6  70.2  42.8  51.6  36.   37.9  33.4  81.7  73.5  27.1
  41.5  32.8  42.9  50.3  57.3  14.3  28.3  43.4  30.7  48.1  32.3  29.7
  37.5  40.2  28.2  58.5  33.3  26.3  78.   48.8  40.1  40.8  43.7  45.9
  37.7  40.7  31.7  36.4  45.   45.4  65.9  33.8  38.6  35.   37.3  38.2
  18.5  25.7  52.2  49.3  36.8  34.7  46.6  22.4  18.8  39.6  49.   36.7
  49.9  29.2  28.5  26.4  44.7  34.9  25.5  26.9  25.4  21.8  24.5  22.5
  52.1  30.9  41.1  31.   30.8  47.9  29.6  46.9  40.6  28.9  23.8  43.
  26.8  22.8  23.   14.9  63.1  60.8  20.5  39.2  32.2  27.7  24.   59.4
  25.6  28.6  36.3  28.4  24.6  29.9  17.   36.2  60.5  38.7  42.2  17.8
  16.   24.4  47.8  24.7  13.2  28.   17.6  21.3  19.6  18.3  15.5  16.3
  21.1  18.1  29.1   8.7  20.2  35.1  27.2  59.3  27.9  26.5  45.1   9.4
  13.3  33.1  20.9  11.   21.4  20.3  18.6  18.2  50.1  13.   29.4  28.7
  21.9  51.   49.7  26.7  19.9  17.5  12.7  27.8  21.    7.4  28.1  32.5
  14.1  11.9  24.2  14.6   8.5  23.7  25.2  55.7  32.   28.8   4.8  15.
  21.7  29.8  19.5  25.3  35.6  52.7  16.2   9.3  22.3  24.9  16.4  11.4
  13.7  36.9  34.8  50.4  12.1  16.9  31.2  43.2  11.8  15.4  23.4  13.6
   9.5  12.3  33.5  10.9  27.4  19.4  14.   32.9  30.2  16.8  18.    5.8
  25.8  17.9  20.8  10.6  31.5   8.6  44.5   5.1  32.7  16.6  19.7  12.5
   8.   18.7  39.8  27.3  19.8  25.9  12.8  11.1  22.2  11.3  33.    7.8
  17.7   9.7  22.7   9.6  31.6  30.5  26.1   8.4   5.9  10.3  17.3   8.8
  25.1  14.5  26.2  19.3  18.9  17.2  12.6  26.6  13.8  13.4   7.1  23.6
  30.    3.8   4.9  33.9   6.    8.2  19.2  10.7  40.    7.3   4.3  11.6
  17.4  20.7   7.2  21.5   9.1   4.   20.   23.2  14.4   6.3  30.1   6.1
   3.1   8.1  22.   21.6   9.2  10.2  30.6  15.7  37.4   7.   15.9   9.
   8.9   6.4  15.1  21.2  13.9   4.1   6.7  15.8  24.1   7.9  20.1  14.2
  16.1  17.1   4.2  19.1   7.5  24.3  15.6  14.8  39.7  16.5  13.1   4.5
  12.   18.4   5.2   9.8  20.4  11.5  25.   16.7   6.2   7.6  20.6  12.9
   6.6  11.7  10.    5.   13.5  14.7  32.4  39.   10.5  10.4   3.7  12.2
   5.6  33.6   7.7  10.1   3.4  10.8   1.   23.5   5.7  11.2  39.3   6.9
   9.9   6.5   2.5   3.2   8.3   5.3  19.   15.2   3.9   3.5   4.6  15.3
   4.7   6.8   2.8   3.6  31.4   3.3  22.6   1.9   5.4   2.7  12.4   5.5
   4.4   1.8]

ER SCORE (589)
[100.   96.3  98.2  99.4  99.2  82.5  91.4  99.3  99.6  98.7  98.8  99.7
  97.4  93.5  88.   79.2  99.8  94.2  98.5  99.1  95.1  91.8  82.6  67.3
  87.5  99.9  96.5  89.4  79.5  69.7  90.4  93.8  97.2  97.8  94.4  72.6
  47.5  95.5  96.7  63.5  95.4  91.   46.7  55.2  80.2  75.6  96.8  64.3
  91.5  64.1  62.1  93.   68.1  75.7  56.5  73.5  72.2  74.8  62.7  85.8
  95.8  95.7  82.1  55.9  86.7  66.4  92.7  90.   61.7  48.1  91.9  53.
  66.7  78.4  87.4  90.1  43.5  41.7  83.3  61.2  49.2  87.9  36.2  81.
  86.5  47.1  63.1  74.9  56.1  70.1  98.6  37.7  57.6  46.3  51.   27.7
  74.2  92.8  95.   60.3  76.4  75.3  81.6  50.6  73.4  79.8  95.9  68.7
  67.5  56.7  77.3  55.5  57.7  81.5  79.4  69.6  29.5  41.6  48.8  62.3
  53.5  46.4  72.1  34.4  58.5  34.8  45.8  20.7  81.9  48.9  62.9  39.1
  76.6  71.5  56.6  86.3  25.7  44.   42.3  68.8  42.1  63.3  43.6  92.
  77.1  42.8  41.2  32.4  54.4  39.3  26.   33.1  93.9  73.9  89.3  63.
  36.   51.7  46.8  28.8  56.3  68.5  43.4  35.3  24.6  40.5  32.6  35.5
  51.8  49.4  50.5  90.5  55.8  40.2  36.1  78.6  38.7  52.7  82.7  31.
  84.7  64.5  38.8  30.5  58.1  24.1  46.2  29.   50.9  41.5  33.7  36.4
  32.2  64.6  35.6   6.8  21.7  29.6  54.3  40.   41.8  41.   85.2  41.9
  85.3  47.9  37.6  62.2  90.9  34.7  78.2  30.   39.5  33.4  16.6  88.7
  70.4  62.8  65.1  39.   27.   21.   20.3  18.8  26.4  23.9  60.6  17.9
  88.3  40.4  13.7  54.7  37.1  20.5  19.3  22.1  36.8  13.9  65.3  44.8
  24.9  44.2  25.   50.3  25.9  32.3  16.3  46.1  40.3  12.2  38.6  63.8
  19.2  77.5  34.5  59.8  17.7  42.6  34.9  43.   58.8  31.7  62.   21.2
  67.8  52.2  24.2  21.8   9.4  26.3  48.6  12.3  32.9  47.6  24.4  51.2
  25.2  17.3  39.4  11.9  55.1  23.7  71.1  20.2  51.5  28.1  76.3  61.8
  48.2  20.8  10.2  16.9  32.8  46.9  15.    8.2  31.3  12.4   9.7  23.5
   5.9  38.9  49.8  19.4  27.1  11.8  15.7  13.8  56.   22.5  24.3  36.6
  62.6  38.   10.7  14.3  43.1  37.5  53.3  19.1  73.3  51.3   9.9  15.5
  27.6   8.7  24.7  12.9  39.9  15.9  21.3  37.3  17.2   4.9  16.4  37.2
  28.2  33.6  72.5  32.1  11.   10.9  52.9  18.7  21.1  28.   22.3  21.6
  19.5  19.8  17.8  10.8  26.7  30.1  30.8  13.6  47.8  31.1   3.1  18.
  21.4  22.8  26.9  11.3  46.   20.6  47.3  14.9  34.1   5.   17.1  14.6
  35.9  18.6  13.1   6.4  72.4  59.9  31.4  39.2  10.    9.6   8.5  20.
  31.6  10.3   9.8  26.6  60.2  37.8  70.   27.4  19.   11.2  55.3  36.7
  30.2  30.4   7.8  14.2  10.6  16.2  17.6  44.6  12.   14.   18.9  10.5
   7.1  24.   38.3  19.9  78.1  18.5  17.4  51.9  14.4  21.5  50.   22.6
  10.4  76.7   2.    7.3  29.7  50.2   4.4   9.5   8.3  23.3  20.9   5.2
  14.7  22.7  11.7  22.9  29.4  59.4  27.3  34.   38.2  23.8  15.4  53.2
   4.6  30.9  16.   21.9  10.1   4.3   5.5   7.9  29.8   4.8  20.4   4.1
  58.6  12.8  35.8  31.5   6.6  22.2  13.   25.5  61.5  13.3  20.1   4.5
   9.2  94.7   7.2   5.8  12.5   2.8   7.5  11.1  11.5  15.1  50.1  33.9
   5.3  12.6  45.3   6.2  43.2  22.   18.3   6.    7.4   2.9  42.5   5.6
  31.9  33.    9.3  16.8  29.1  17.5  22.4  32.7  31.2   8.1  27.8  43.9
  30.6  28.7   9.1   8.   49.    9.    6.5  57.5  25.8  18.2   8.8   6.1
  49.1   7.    2.3   7.6   3.8  11.4  44.7  12.1  41.3  33.3   5.4   4.7
  13.5   1.8   3.6  13.4  45.9  15.6  15.3  32.   14.5   2.1   6.3   3.7
   2.7  56.4  36.5   8.4  19.7   3.5   6.7   7.7   4.   15.2  11.6   1.4
  23.   54.1   5.1  28.4   4.2  27.2   8.9  33.5  23.4  14.1  16.1  15.8
  23.1   3.2  12.7   3.4   3.    3.3   6.9   1.6  16.5   5.7   1.9  24.5
  14.8  25.3  16.7  26.8   2.6   3.9  31.8  18.4   2.2   1.2   1.   17.
   2.5]

CPF SCORE (628)
[100.   95.   99.7  91.   88.6  98.8  95.9  80.9  96.6  94.6  78.1  99.2
  72.   98.   99.6  97.2  94.8  96.9  64.8  93.1  92.6  85.8  94.3  72.4
  85.1  68.8  92.8  70.2  91.7  54.3  56.8  93.   69.9  44.5  81.2  70.9
  97.3  71.2  94.2  54.5  84.3  84.6  67.9  83.2  98.6  87.2  98.7  31.7
  64.   50.9  62.3  47.4  94.7  68.2  47.1  79.1  80.3  93.2  85.4  82.2
  42.4  81.6  56.6  43.6  66.   56.1  88.2  44.8  41.4  69.2  69.8  67.2
   2.3  54.2  48.8  87.8  61.9  62.4  65.8  68.4  55.9  42.9  71.5  99.3
  48.6  77.1  53.9  52.3  36.6  98.3  99.   77.9   7.3  79.7  90.9  40.3
  35.5  83.4  28.1  73.3  51.3  79.6  66.5  14.2  62.7  62.   64.9  67.7
  88.3  91.3  30.1  62.9  82.9  43.4  74.1  75.9  99.4  38.3  38.4   4.1
  49.1  51.9  81.9  75.7  47.9  65.6  75.5  34.3  66.2  73.6  53.   61.7
  75.4  93.5  22.2  57.8  54.8  55.8  70.3  77.5  47.8  61.2  32.4  38.2
   2.1  62.6  26.3  53.8  42.7  34.2  76.2  61.5  18.2  73.5  83.9  90.2
  42.2  85.7  89.6  95.6   4.8  12.8   3.9  33.8  56.3  59.5  54.6  63.
  80.7  63.2  71.1  71.8  57.5  66.4  45.4  39.8  77.   89.2  26.5  86.2
  24.9  60.5  49.2  10.8  34.7  69.   32.2  97.    9.4  58.6  99.9  84.8
  12.5  84.1   3.   50.6  95.2  60.3  35.1  50.5  51.4  96.7  37.2  54.4
  37.8  71.7  41.9  44.3  68.1  25.8  82.3  52.7  56.9  57.2  21.    5.4
  99.8  96.4   6.9  48.2  25.3  74.4  14.3  70.6  45.1  75.1  34.4   8.6
  10.   43.8  72.9  36.5  72.6  60.7  73.2  57.7  41.7  82.1  24.   21.7
  61.8   2.5  42.5  40.2  43.   53.1  66.3  36.7  27.7  35.3  36.   92.5
   8.1  67.5  10.4  97.8  77.2  31.2  59.6  45.2  55.2  99.5  64.2  48.4
  72.8   2.   13.8  51.8  91.1  52.6  44.2  37.6  16.5  52.2  25.9   1.7
  39.5  52.5  19.6  39.2  97.1  74.5  46.8   6.   67.1  61.4  33.3  17.7
  15.5  30.   97.5  93.9  65.5   9.   78.7  38.7  19.1   3.2  39.6   4.7
  22.5  23.7  32.3   2.7  12.4   7.9  71.9  12.2  55.5  33.7  64.3  91.6
  35.9  92.2  93.6  27.   56.7  58.3  25.   34.5  49.7  33.2  22.   25.2
  90.1   6.2  87.   58.8  31.5  73.9  47.7  72.3  18.8  29.7  20.6  31.
   9.6  54.7   3.8  38.   10.2  79.5  33.4  61.   18.1  22.8   2.9  12.3
  13.   41.   32.   48.5  13.6  58.7  29.8   4.2  15.1  53.7  16.7  17.2
  95.7  76.   19.4  28.4  40.   60.4   9.5   7.8   5.6  12.7  50.8  85.6
  20.8  39.7  82.6   7.   93.8  30.9   3.4   2.2   1.2  29.6  71.    3.5
  36.3  33.   26.8   8.8  36.9  11.8  27.4  33.5  10.7  11.   75.3  56.
  24.4  58.2  34.1  30.6   4.   64.1  30.2  17.   14.8   8.9   7.4  44.4
  16.6  63.8  38.6  97.7  14.6  13.7   2.8   9.1  22.7  17.5  18.   65.1
   9.3   7.6  25.6  36.4  47.5  11.2  21.8  60.2  69.3   4.9  57.9  19.
   4.5   6.4  20.9  29.9  82.7  41.1  27.8   5.1   1.3  87.7  27.6  69.6
  37.1  23.5  12.1   1.8  15.6  19.2  27.3  23.8  16.8  22.6   6.3  12.
  11.6  85.    6.8  59.4  20.7  43.7  36.8  84.   41.5  39.3  14.7  82.5
  60.9  11.1   5.    1.9  74.8  94.5  31.3  15.7  13.3   3.3   4.6  81.5
   1.4  29.1  16.4  21.4  22.3  86.1  68.3  79.9  15.3   9.7  37.7  24.6
  31.9   1.1   2.6  89.5   7.2   3.1   9.2  26.   23.9  49.4  10.1  48.7
  24.7  20.4   8.   30.8  72.2  40.6   8.3   4.3  48.   33.9  18.6   5.5
   6.1   7.1   4.4  12.9  32.1  53.2  55.4  17.8  13.4  13.2  11.9  10.3
   1.5  29.4  25.5  28.5  72.1  64.7  57.3  16.3   2.4  15.8  46.9  55.3
  45.   28.9  43.1  15.2  20.   50.1  24.3   1.   40.1  21.9  11.5  65.
  21.3  32.5  18.7  24.2  10.9  50.   40.7   5.2   5.3  10.6  22.1  31.6
   8.5  43.5  20.3   9.9  44.1  19.9  30.5  11.7   3.7  14.9  13.9  47.3
  24.8  55.6  42.8   6.6  11.4   3.6  34.9  23.3  41.2   5.8  19.5   6.5
  13.1  15.4  37.5  13.5  16.   12.6   6.7  23.4  31.8  14.   18.9   7.7
  28.8  17.9   1.6   9.8  47.2  45.9  21.5  24.1  30.7  25.7  28.3  23.
  32.8  16.2  11.3  19.7  30.3  28.6   8.7  18.5  20.2   8.2   7.5   5.7
  14.5   8.4   5.9  27.5]

EO SCORE (622)
[100.   95.9  95.   89.3  49.1  99.8  87.7  97.   99.3  98.3  98.7  47.3
  57.3  84.1  98.9  95.8  97.5  99.4  73.3  76.4  67.1  91.2  69.7  91.9
  86.7  84.9  99.1  99.5  66.6  76.6  98.   66.   88.2  74.4  94.4  63.1
  79.9  90.3  74.1  99.9  85.9  76.8  77.7  83.5  93.6  95.6  48.5  96.9
  40.8  97.8  93.9  81.9  82.9  92.5  96.1  84.2  75.3  95.3  54.7  82.6
  72.7  44.5  34.6  70.4  79.2  33.5  62.9  58.6  86.9  46.9  81.   51.4
  47.9  53.6  77.1  52.3  53.7  61.5  72.   90.8  16.   39.7  73.2  55.9
  60.5  98.8  36.5  40.1  91.   28.9  97.1  38.   94.2  92.2  61.2  45.7
  86.6  67.5  50.5  49.9  44.2  35.5  91.5  72.6  27.5  79.4  50.7  42.8
  23.2  29.1  97.9  40.5  67.4  62.2  33.1  94.   74.   63.8  47.6  90.5
  53.5  47.8  97.7  92.8  19.9  32.9  40.9  38.2  74.9  54.5  77.   75.6
  44.9  39.2  53.3  66.2  55.1  65.4  41.   26.4  20.9  30.4  42.2  60.
  97.6  25.4  12.6  33.4  25.6  45.8  42.4  37.9  37.2  25.8  58.9  97.4
  97.3  87.2  92.3  82.   57.6  56.4  90.7  68.7  75.8  19.5  47.2  71.
  56.3  32.6  17.9  52.5  43.6  50.   59.7  67.2  98.4  67.9  61.1  47.7
  12.5  15.1  96.4  75.9  33.2  20.8  74.8  87.9  60.7  27.1  28.   32.5
  29.6  51.2  49.6  77.6  37.8   6.8  23.   49.5  18.2  57.5   5.2  46.
  68.6  35.2  38.7  84.3  22.5  87.4  30.   80.5  30.7  26.6  82.2  13.3
  60.6  37.7  64.5  38.8  34.9  60.3  58.4  39.8  96.   56.8  37.   24.
  54.1  69.5  13.7  22.8  75.4  63.2  79.7  48.9  26.3  88.9  27.   34.
  69.6  65.8  50.8   3.9  35.8  59.6  25.   28.7   7.5  89.9  10.1  31.8
  58.1  10.8  21.   90.1  31.   59.4  44.6  19.3  21.6  33.    8.7  70.
  69.3  69.4  36.4  26.8  54.4  30.6   1.3  25.1  50.6  23.1  65.9  69.9
  45.3  18.1  27.8   8.5  85.8  17.4  21.2  41.1  15.6  84.8  89.2  80.8
  46.1  14.3  58.2   2.5  88.7   3.4  83.1  26.   80.1  40.4  44.3  88.6
  58.8  54.3  28.8   2.2  15.5  17.7   1.8   9.6  35.7  28.3  21.4  10.4
  44.   11.8  11.9  13.1  14.7  12.8  36.9  17.8  45.1  61.4  42.7  23.4
  40.2   5.1  43.7  11.   17.   45.    3.3  29.2  29.8  22.4  24.9  42.1
  20.4  15.2  29.   13.9  16.5  18.8  14.5  20.3  81.2  11.2  36.8  19.4
   7.   91.3  61.3  16.2  19.6   1.6  31.9  54.6   5.4  24.7  32.3   5.8
  12.3   4.1  24.5  24.8  22.1  15.3  18.9   4.2  17.3  12.4  21.8   6.4
  48.3   7.1   7.4   1.4  15.9  17.5   2.9  16.4  25.3  10.9   9.4   5.
  11.5  86.1  19.1  28.4  80.4  38.1  41.5  38.9  45.4  89.8   5.3   5.6
  64.8  29.5   7.6  16.6  47.1   2.7  98.1  10.5   4.9  15.   89.4  34.4
  34.8  20.   90.6  48.4  67.3   7.3  18.4  20.6   6.1  25.9  16.9  10.3
  83.6  15.7  29.4  30.8  73.4   1.7  87.1   4.8  69.2  51.6  18.7   9.3
   4.4  11.6  17.6  50.9  29.3   6.6  46.2   9.1  93.3  25.2  11.1  31.3
  13.8   6.7  11.4  24.2  31.2  78.8   8.8   4.5  41.8  13.5   6.2  14.8
  17.1   4.   19.2  39.5  14.9  69.8  23.7  16.3   6.9   3.1   8.3   6.5
  55.    2.1   9.   44.1  45.6   3.6  87.   26.2  11.3  64.1   2.   13.6
  27.7  15.8  41.3   8.9   2.8   4.3  48.    3.5  73.5  35.3  40.3  20.1
   7.7   9.8   3.8   3.    4.7  28.1  26.7  30.5  55.2  58.    1.9  85.6
   9.7   6.3  22.3   6.   35.9  29.9  10.7  61.6  43.1  22.6  57.7  24.4
   4.6  34.1   5.9  25.5  12.2  12.1   5.7  51.5  80.   24.6  48.8   3.7
  49.   86.   13.4  36.3  19.7  92.    2.3  34.2  18.5  70.3   8.6  35.6
  12.7   1.2  31.4  23.6  96.8  12.9  16.7  42.3  11.7  39.6  27.4  45.2
  71.4  18.3   7.8  33.9  22.   95.2   7.9   8.2  21.3   5.5  14.4  51.8
  41.2  53.   55.5   3.2  16.8  28.6  13.    7.2  35.4  24.1  53.2  27.9
  42.9  13.2   9.5  32.1  62.4  12.   71.8  27.6  42.   18.    2.4  64.4
  76.   37.5  52.2  14.1  76.2  90.4   9.2   8.   10.6  38.6  90.   38.3
  49.7   2.6  26.1  51.7  27.3  42.5  17.2   1.   21.9  26.5  30.3  73.8
   1.5   8.4  58.5  14.2  39.   89.1  32.8  10.   16.1  15.4]

In [16]:
df.dtypes

Country/Territory     object
Region                object
Research              object
AR SCORE             float64
ER SCORE             float64
CPF SCORE            float64
EO SCORE             float64
dtype: object

In [17]:
df.rename(columns={
    "Country/Territory": "Country",
    "AR SCORE": "Academic_Reputation",
    "ER SCORE": "Employer_Reputation",
    "CPF SCORE": "Research_Quality",    #citations per faculty: measures research quality and output
    "EO SCORE": "Employment_Outcomes"
}, inplace=True)

In [18]:
df

,Country,Region,Research,Academic_Reputation,Employer_Reputation,Research_Quality,Employment_Outcomes
0,United States of America,Americas,VH,100.0,100.0,100.0,100.0
1,United Kingdom,Europe,VH,99.6,100.0,95.0,95.9
2,United States of America,Americas,VH,100.0,100.0,99.7,100.0
3,United Kingdom,Europe,VH,100.0,100.0,91.0,100.0
4,United States of America,Americas,VH,100.0,100.0,100.0,100.0
...,...,...,...,...,...,...,...
1496,Czechia,Europe,VH,7.2,5.3,7.9,15.5
1497,Russian Federation,Europe,HI,5.7,4.7,1.6,3.5
1498,Thailand,Asia,MD,8.3,2.7,5.6,3.2
1499,Japan,Asia,HI,4.4,2.9,8.2,1.7
1500,Republic of Korea,Asia,MD,6.5,11.9,2.0,1.9

In [19]:
# df.to_csv("qs_clean.csv", index=False)